"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.get = exports.Name = void 0;
const sysconf = require("../index.node");
var Name;
(function (Name) {
    Name[Name["_SC_ARG_MAX"] = sysconf._SC_ARG_MAX] = "_SC_ARG_MAX";
    Name[Name["_SC_CHILD_MAX"] = sysconf._SC_CHILD_MAX] = "_SC_CHILD_MAX";
    Name[Name["_SC_HOST_NAME_MAX"] = sysconf._SC_HOST_NAME_MAX] = "_SC_HOST_NAME_MAX";
    Name[Name["_SC_LOGIN_NAME_MAX"] = sysconf._SC_LOGIN_NAME_MAX] = "_SC_LOGIN_NAME_MAX";
    Name[Name["_SC_NGROUPS_MAX"] = sysconf._SC_NGROUPS_MAX] = "_SC_NGROUPS_MAX";
    Name[Name["_SC_CLK_TCK"] = sysconf._SC_CLK_TCK] = "_SC_CLK_TCK";
    Name[Name["_SC_OPEN_MAX"] = sysconf._SC_OPEN_MAX] = "_SC_OPEN_MAX";
    Name[Name["_SC_PAGESIZE"] = sysconf._SC_PAGESIZE] = "_SC_PAGESIZE";
    Name[Name["_SC_PAGE_SIZE"] = sysconf._SC_PAGE_SIZE] = "_SC_PAGE_SIZE";
    Name[Name["_SC_RE_DUP_MAX"] = sysconf._SC_RE_DUP_MAX] = "_SC_RE_DUP_MAX";
    Name[Name["_SC_STREAM_MAX"] = sysconf._SC_STREAM_MAX] = "_SC_STREAM_MAX";
    Name[Name["_SC_SYMLOOP_MAX"] = sysconf._SC_SYMLOOP_MAX] = "_SC_SYMLOOP_MAX";
    Name[Name["_SC_TTY_NAME_MAX"] = sysconf._SC_TTY_NAME_MAX] = "_SC_TTY_NAME_MAX";
    Name[Name["_SC_TZNAME_MAX"] = sysconf._SC_TZNAME_MAX] = "_SC_TZNAME_MAX";
    Name[Name["_SC_VERSION"] = sysconf._SC_VERSION] = "_SC_VERSION";
    Name[Name["_SC_BC_BASE_MAX"] = sysconf._SC_BC_BASE_MAX] = "_SC_BC_BASE_MAX";
    Name[Name["_SC_BC_DIM_MAX"] = sysconf._SC_BC_DIM_MAX] = "_SC_BC_DIM_MAX";
    Name[Name["_SC_BC_SCALE_MAX"] = sysconf._SC_BC_SCALE_MAX] = "_SC_BC_SCALE_MAX";
    Name[Name["_SC_BC_STRING_MAX"] = sysconf._SC_BC_STRING_MAX] = "_SC_BC_STRING_MAX";
    Name[Name["_SC_COLL_WEIGHTS_MAX"] = sysconf._SC_COLL_WEIGHTS_MAX] = "_SC_COLL_WEIGHTS_MAX";
    Name[Name["_SC_EXPR_NEST_MAX"] = sysconf._SC_EXPR_NEST_MAX] = "_SC_EXPR_NEST_MAX";
    Name[Name["_SC_LINE_MAX"] = sysconf._SC_LINE_MAX] = "_SC_LINE_MAX";
    Name[Name["_SC_2_VERSION"] = sysconf._SC_2_VERSION] = "_SC_2_VERSION";
    Name[Name["_SC_2_C_DEV"] = sysconf._SC_2_C_DEV] = "_SC_2_C_DEV";
    Name[Name["_SC_2_FORT_DEV"] = sysconf._SC_2_FORT_DEV] = "_SC_2_FORT_DEV";
    Name[Name["_SC_2_FORT_RUN"] = sysconf._SC_2_FORT_RUN] = "_SC_2_FORT_RUN";
    Name[Name["_SC_2_LOCALEDEF"] = sysconf._SC_2_LOCALEDEF] = "_SC_2_LOCALEDEF";
    Name[Name["_SC_2_SW_DEV"] = sysconf._SC_2_SW_DEV] = "_SC_2_SW_DEV";
    Name[Name["_SC_PHYS_PAGES"] = sysconf._SC_PHYS_PAGES] = "_SC_PHYS_PAGES";
    Name[Name["_SC_AVPHYS_PAGES"] = sysconf._SC_AVPHYS_PAGES] = "_SC_AVPHYS_PAGES";
    Name[Name["_SC_NPROCESSORS_CONF"] = sysconf._SC_NPROCESSORS_CONF] = "_SC_NPROCESSORS_CONF";
    Name[Name["_SC_NPROCESSORS_ONLN"] = sysconf._SC_NPROCESSORS_ONLN] = "_SC_NPROCESSORS_ONLN";
})(Name = exports.Name || (exports.Name = {}));
const get = (name) => {
    return sysconf.get(name);
};
exports.get = get;
